name: build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: gradle build --stacktrace
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: custom-pickaxe
          path: build/libs/*.jar
